sudo: false
language: python
cache: pip
matrix:
    include:
        - env: TARGET=hpat
        - env: TARGET=umap
        - env: TARGET=librosa
        - env: TARGET=clifford
script:
- ./switchboard.py -t $TARGET
notifications:
    email: false
